### ISSUE TITLE
Problem with socketio

### ISSUE THREAD

**Issue by andrecrjr** [greymass/ual-anchor#15]
Hey guys, I'm having a problem with socketio, all my bussiness rule is on a websocket server, that waits from ual-anchor(Anchor transport link) to get the user account, and when I click on **Launch Anchor**, just close connection(Transport not open) to my websocket, are there some workaround to prevent this?

I'm on Brave(Chromium)

**Comment by aaroncox** [comment]
We'll have to take a look - I know this was happening in Firefox at one point and we deployed a fix for it, I wasn't expecting this to also be happening in Brave.

**Comment by aaroncox** [comment]
Give `ual-anchor@1.0.4` a try and let me know if that resolves the issue you're running into.

**Comment by andrecrjr** [comment]
it worked, thanks so much!

**Comment by aaroncox** [comment]
No problem! Thanks for letting us know 👍
