### ISSUE TITLE
TypeError: user is undefined

### ISSUE THREAD

**Issue by makc** [greymass/ual-anchor#16]
I think this happens when you click "go back" link without logging in, but not sure:
![Screen Shot 2021-03-24 at 3 27 35 ](https://user-images.githubusercontent.com/242577/112245472-3c7d0d00-8c51-11eb-901c-6b073122e171.png)

**Comment by aaroncox** [comment]
Good catch - this should be a pretty easy fix. It looks like UAL is trying to call the `logout` function whenever you hit the back button, and our adapter wasn't expecting UAL to call `logout` unless the user was actually logged in. Thanks!

**Comment by aaroncox** [comment]
This should be resolved now with the release of 1.0.5. If the issue persists, feel free to reopen!
