### ISSUE TITLE
webpack not works 

### ISSUE THREAD

**Issue by azarzaza** [greymass/ual-anchor#24]
![image](https://user-images.githubusercontent.com/23259321/135334736-65105131-c8f9-4f8f-b930-5c92a24eb275.png)
getting this error when try to webpack the ual-anchor

**Comment by aaroncox** [comment]
We made some changes to the underlying libraries and just published `ual-anchor@1.1.1`, which should now resolve this problem. If you're still having issues after upgrading `ual-anchor`, let us know!
